package com.animeinjection.weeblist.api.objects;

public class Media {
  public int id;
  public int idMal;
  public MediaTitle title;
  public MediaType type;
  public MediaFormat format;
  public MediaStatus status;
  public String description;
  public FuzzyDate startDate;
  public FuzzyDate endDate;
  public MediaSeason season;
  public int episodes;
  public int duration;
  public int chapters;
  public int volumes;
//  public CountryCode countryOfOrigin;
  public boolean isLicensed;
//  public MediaSource source;
  public String hashtag;
//  public MediaTrailer trailer;
  public int updatedAt;
  public MediaCoverImage coverImage;
  public String bannerImage;
  public String[] genres;
  public String[] synonyms;
  public int averageScore;
  public int meanScore;
  public int popularity;
  public int trending;
//  public MediaTag[] tags;
//  public MediaConnection relations;
//  public CharacterConnection[] characters;
//  public StaffConnection[] staff;
//  public StudioConnection[] studios;
  public boolean isFavorite;
  public boolean isAdult;
//  public AiringSchedule nextAiringEpisode;
//  public AiringScheduleConnection[] airingSchedule;
//  public MediaTrendConnection[] trends;
//  public MediaExternalLink[] externalLinks;
//  public MediaStreamingEpisodes[] streamingEpisodes;
//  public MediaRank[] rankings;
  public MediaListEntry mediaListEntry;
//  public ReviewConnection[] reviews;
//  public MediaStats stats;
  public String siteUrl;
  public boolean autoCreateForumThread;
  public String modNotes;
}
